In [1]:
pip install -e ..

Obtaining file:///home/sagar/winogender_contextuality
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Building wheels for collected packages: winogender_contextuality
  Building editable for winogender_contextuality (pyproject.toml) ... done
  Created wheel for winogender_contextuality: filename=winogender_contextuality-0.0.1-py3-none-any.whl size=3680 sha256=7eaeda3a55298dce1ac4d00ae011d0f0629bc206b66dd3eb3821d0ed21b9bdb9
  Stored in directory: /tmp/pip-ephem-wheel-cache-e7nb69x4/wheels/f6/b9/38/03ac5a5ccd63b90faa34c1614fd3e708a9c34ab8edb44270e9
Successfully built winogender_contextuality
Installing collected packages: winogender_contextuality
  Attempting uninstall: winogender_contextuality
    Found existing installation: winogender_contextuality 0.0.1
    Uninstalling winogender_contextuality-0.0.1:
      Successfully uninstalled winogender_contextuality-0.0.1
Successfully installed winogender_contextuality-0.0.1
Note: you may need to restart the kernel to use updated packages.

In [2]:
from winogender_contextuality.utils import *
from winogender_contextuality.modeling.contextuality import *
from winogender_contextuality.config import *

2025-10-24 13:36:57.177 | INFO     | winogender_contextuality.config:<module>:13 - PROJ_ROOT path is: /home/sagar/winogender_contextuality
2025-10-24 13:36:57.178 | INFO     | winogender_contextuality.config:<module>:17 - DATA_ROOT path is: /data_users1/sagar/winogender_contextuality

In [3]:
import pandas as pd

In [4]:
## Investigating the Dataset

In [32]:
raw_data = pd.read_csv(RAW_DATA_DIR/"data/new_templates.tsv", sep="\t")

In [33]:
raw_data

,occupation(0),other-participant(1),answer,pronoun_type,template,single_version
0,technician,customer,1,$NOM_PRONOUN,The $OCCUPATION told the $PARTICIPANT that $NO...,The $PARTICIPANT was told that $NOM_PRONOUN co...
1,technician,customer,0,$NOM_PRONOUN,The $OCCUPATION told the $PARTICIPANT that $NO...,The $OCCUPATION said that $NOM_PRONOUN had com...
2,technician,customer,1,$ACC_PRONOUN,The $OCCUPATION had to call the $PARTICIPANT f...,The $PARTICIPANT received a call for $ACC_PRON...
3,technician,customer,0,$ACC_PRONOUN,The $OCCUPATION had to call the $PARTICIPANT f...,The $OCCUPATION called for $ACC_PRONOUN to con...
4,technician,customer,1,$POSS_PRONOUN,The $PARTICIPANT told the $OCCUPATION that $PO...,The $PARTICIPANT said that $POSS_PRONOUN fridg...
...,...,...,...,...,...,...
355,secretary,visitor,1,$NOM_PRONOUN,The $OCCUPATION asked the $PARTICIPANT to sign...,The $PARTICIPANT was asked to sign in so that ...
356,secretary,visitor,0,$ACC_PRONOUN,The $OCCUPATION requested the name of the $PAR...,The $OCCUPATION needed information for $ACC_PR...
357,secretary,visitor,1,$ACC_PRONOUN,The $OCCUPATION requested the name of the $PAR...,The $PARTICIPANT needed to provide information...
358,secretary,visitor,0,$POSS_PRONOUN,The $OCCUPATION informed the $PARTICIPANT that...,The $OCCUPATION said that $POSS_PRONOUN boss w...
359,secretary,visitor,1,$POSS_PRONOUN,The $OCCUPATION informed the $PARTICIPANT that...,The $PARTICIPANT was informed that $POSS_PRONO...

In [34]:
wp_pairs = pd.read_csv(INTERIM_DATA_DIR/"winopron_pairs.tsv", sep="\t")

In [40]:
wp_pairs.head()

,template_1,differences_1,case_1,referent_1,template_2,differences_2,case_2,referent_2
0,The technician told the customer that BLANK co...,"['he', 'she']",$NOM_PRONOUN,customer,The technician told the customer that BLANK ha...,"['he', 'she']",$NOM_PRONOUN,technician
1,The technician had to call the customer for BL...,"['him', 'her']",$ACC_PRONOUN,customer,The technician had to call the customer for BL...,"['him', 'her']",$ACC_PRONOUN,technician
2,The customer told the technician that BLANK fr...,"['his', 'her']",$POSS_PRONOUN,customer,The customer told the technician that BLANK ch...,"['his', 'her']",$POSS_PRONOUN,technician
3,The taxpayer met with the accountant to find o...,"['he', 'she']",$NOM_PRONOUN,taxpayer,The taxpayer met with the accountant to find o...,"['he', 'she']",$NOM_PRONOUN,accountant
4,The taxpayer met with the accountant for BLANK...,"['him', 'her']",$ACC_PRONOUN,taxpayer,The taxpayer met with the accountant for BLANK...,"['him', 'her']",$ACC_PRONOUN,accountant